'use strict';
const fs = require('fs'); const http = require('http'); const os = require('os'); const path = require('path'); const { EventEmitter } = require('events');
const { createRuntimeService, nodeCompatibility } = require('../install/runtimeService');
const { createBrowserInstallManager, defaultInstaller } = require('../install/browserInstallManager');
const { createHuntRunManager } = require('../run/huntRunManager');
const { acquireUiLock, releaseUiLock, inspectUiLock } = require('../runtime/uiLock');
const { createScheduleStore, validateSchedule } = require('../scheduler/scheduleStore');
const { createLocalScheduler, calculateNextRun } = require('../scheduler/localScheduler');
const { startServer, installShutdownHandlers, startupErrorMessage } = require('../ui/server'); const runtime = require('../runtime');
let passed = 0; let failed = 0;
function ok(name, value) { if (value) { passed++; console.log(`  [PASS] ${name}`); } else { failed++; console.log(`  [FAIL] ${name}`); } }
function temp(name) { return fs.mkdtempSync(path.join(os.tmpdir(), `jh-${name}-`)); }
function tick() { return new Promise((resolve) => setImmediate(resolve)); }
function request(server, pathname) { return new Promise((resolve, reject) => { const req = http.get({ hostname: '127.0.0.1', port: server.address().port, path: pathname }, (res) => { let body = ''; res.on('data', (c) => { body += c; }); res.on('end', () => resolve({ status: res.statusCode, json: JSON.parse(body) })); }); req.on('error', reject); }); }
function apiRequest(server, method, pathname, body) { return new Promise((resolve, reject) => { const text = body === undefined ? '' : JSON.stringify(body); const req = http.request({ hostname: '127.0.0.1', port: server.address().port, path: pathname, method, headers: text ? { 'Content-Type': 'application/json', 'Content-Length': Buffer.byteLength(text) } : {} }, (res) => { let response = ''; res.on('data', (chunk) => { response += chunk; }); res.on('end', () => resolve({ status: res.statusCode, json: JSON.parse(response) })); }); req.on('error', reject); if (text) req.write(text); req.end(); }); }

async function run() {
  console.log('\n### Runtime/bootstrap');
  const cwd = process.cwd(); process.chdir(os.tmpdir()); ok('1. paths independientes de cwd', runtime.PROJECT_ROOT === path.resolve(__dirname, '../..')); process.chdir(cwd);
  ok('2. runtime dir centralizado', runtime.RUNTIME_DIR === path.join(runtime.PROJECT_ROOT, 'runtime-managed'));
  ok('3. APP/DATA/RUNTIME separados', runtime.APP_DIR !== runtime.DATA_DIR && runtime.RUNTIME_DIR !== runtime.DATA_DIR);
  const data = temp('data'); const managed = temp('managed'); const app = temp('app'); const marker = path.join(data, 'jobs', 'keep.json'); fs.mkdirSync(path.dirname(marker), { recursive: true }); fs.writeFileSync(marker, 'keep');
  fs.mkdirSync(path.join(app, 'node_modules', 'playwright'), { recursive: true }); fs.writeFileSync(path.join(app, 'node_modules', 'playwright', 'package.json'), '{}');
  const service = createRuntimeService({ dataDir: data, runtimeDir: managed, appDir: app, nodeVersion: 'v22.20.0', platform: 'win32', browserExecutable: () => path.join(data, 'missing.exe'), resolveModule: () => path.join(app, 'node_modules', 'playwright', 'index.js') });
  service.bootstrap(); service.bootstrap(); ok('4. bootstrap idempotente', fs.existsSync(path.join(data, 'config')) && fs.existsSync(managed));
  ok('5. bootstrap no borra datos', fs.readFileSync(marker, 'utf8') === 'keep');
  ok('6. missing Node controlado', nodeCompatibility(null).state === 'missing'); ok('7. incompatible Node controlado', nodeCompatibility('v20.1.0').state === 'incompatible'); ok('8. Node 22 aceptado', nodeCompatibility('v22.1.0').compatible);
  const oldPath = process.env.PATH; service.bootstrap(); ok('9. no modifica PATH', process.env.PATH === oldPath);
  const exe = path.join(data, 'chromium.exe'); fs.writeFileSync(exe, 'mock'); ok('10. browser disponible detectado', createRuntimeService({ dataDir: data, runtimeDir: managed, appDir: app, nodeVersion: 'v22.1.0', browserExecutable: () => exe, resolveModule: () => 'playwright' }).getStatus().chromium === 'ready'); ok('11. browser missing detectado', service.getStatus().chromium === 'missing');
  const missingDeps = createRuntimeService({ dataDir: temp('missing-deps-data'), runtimeDir: temp('missing-deps-runtime'), appDir: temp('missing-deps-app'), nodeVersion: 'v22.1.0', platform: 'win32' }); let missingDepsCode; try { missingDeps.bootstrap(); } catch (e) { missingDepsCode = e.code; } ok('11a. dependencies missing bloquea bootstrap', missingDepsCode === 'DEPENDENCIES_MISSING');
  const invalidApp = temp('invalid-app'); fs.mkdirSync(path.join(invalidApp, 'node_modules', 'playwright'), { recursive: true }); fs.writeFileSync(path.join(invalidApp, 'node_modules', 'playwright', 'package.json'), '{}'); const invalidDeps = createRuntimeService({ dataDir: temp('invalid-data'), runtimeDir: temp('invalid-runtime'), appDir: invalidApp, nodeVersion: 'v22.1.0', platform: 'win32', resolveModule: () => { throw new Error('invalid'); } }); let invalidDepsCode; try { invalidDeps.bootstrap(); } catch (e) { invalidDepsCode = e.code; } ok('11b. dependencies invalid bloquea bootstrap', invalidDepsCode === 'DEPENDENCIES_INVALID');
  ok('11c. Chromium missing no bloquea bootstrap', service.bootstrap().chromium === 'missing');
  ok('11d. browser administrado pertenece a RUNTIME_DIR', runtime.PLAYWRIGHT_BROWSERS_DIR === path.join(runtime.RUNTIME_DIR, 'playwright-browsers'));

  console.log('\n### UI lifecycle/health');
  const lockPath = path.join(temp('lock'), 'ui.lock'); acquireUiLock(lockPath); ok('12. ui lock adquirido', inspectUiLock(lockPath).busy); let held; try { acquireUiLock(lockPath); } catch (e) { held = e.code; } ok('13. segunda UI bloqueada', held === 'UI_LOCK_HELD'); ok('14. live lock no eliminado', fs.existsSync(lockPath)); releaseUiLock(lockPath);
  fs.writeFileSync(lockPath, JSON.stringify({ pid: 2147483640 })); acquireUiLock(lockPath); ok('15. stale lock recuperado', inspectUiLock(lockPath).busy); releaseUiLock(lockPath);
  let released = 0; let closed = 0; let stopped = 0; const setup = { getStatus: () => ({ readyForHunt: false }) }; const session = { close: async () => { closed++; }, isOpen: () => false, getStatus: async () => ({}) };
  const scheduler = { stop: () => { stopped++; }, getStatus: () => ({ enabled: false, daysOfWeek: [], time: '09:00', nextRunAt: null, lastRunAt: null, lastStatus: null }), update: (v) => v };
  const server = startServer({ port: 0, acquireUiLock: () => {}, releaseUiLock: () => { released++; }, jobService: {}, setupService: setup, linkedinSessionService: session, huntRunManager: {}, scheduler, runtimeService: { getStatus: () => ({}) }, browserInstallManager: { start: () => ({}), getStatus: () => ({}) } }); if (!server.listening) await new Promise((r) => server.once('listening', r));
  const health = await request(server, '/api/health'); ok('16. health seguro responde', health.status === 200 && health.json.status === 'ok' && health.json.app === 'job-hunter'); ok('17. health incluye versión', health.json.version === require('../../package.json').version); ok('18. health no expone paths/secrets', Object.keys(health.json).sort().join(',') === 'app,setupReady,status,version');
  const apiScheduleFile = path.join(temp('schedule-api'), 'config', 'schedule.json'); const apiStore = createScheduleStore({ filePath: apiScheduleFile }); const apiManager = { start: async () => ({ runId: 'api' }), waitForRun: async () => ({ runId: 'api', status: 'COMPLETED' }) }; const apiScheduler = createLocalScheduler({ scheduleStore: apiStore, huntRunManager: apiManager, setTimeout: () => ({ unref() {} }), clearTimeout: () => {} }); apiScheduler.start(); const apiServer = startServer({ port: 0, jobService: {}, setupService: setup, linkedinSessionService: session, huntRunManager: apiManager, scheduler: apiScheduler, runtimeService: { getStatus: () => ({}) }, browserInstallManager: { start: () => ({}), getStatus: () => ({ status: 'IDLE' }) } }); if (!apiServer.listening) await new Promise((resolve) => apiServer.once('listening', resolve)); const invalidScheduleResponse = await apiRequest(apiServer, 'PUT', '/api/schedule', { enabled: 'yes', daysOfWeek: [1], time: '09:00' }); ok('18a. PUT inválido devuelve 400 seguro', invalidScheduleResponse.status === 400 && invalidScheduleResponse.json.code === 'INVALID_SCHEDULE'); const validScheduleResponse = await apiRequest(apiServer, 'PUT', '/api/schedule', { enabled: true, daysOfWeek: [1, 2], time: '10:30' }); ok('18b. PUT válido guarda y replantea', validScheduleResponse.status === 200 && validScheduleResponse.json.enabled && !!validScheduleResponse.json.nextRunAt && fs.existsSync(apiScheduleFile)); const safeScheduleResponse = await request(apiServer, '/api/schedule/status'); ok('18c. GET schedule es seguro', safeScheduleResponse.status === 200 && Object.keys(safeScheduleResponse.json).sort().join(',') === 'daysOfWeek,enabled,lastRunAt,lastStatus,nextRunAt,time'); await new Promise((resolve) => apiServer.close(resolve));
  const shutdown = installShutdownHandlers(server, { linkedinSessionService: session, scheduler }); await shutdown(); ok('19. shutdown libera ui lock', released === 1); ok('20. shutdown cierra session', closed === 1); ok('21. shutdown detiene scheduler', stopped === 1); ok('22. shutdown preserva datos/profile', fs.existsSync(marker));

  let heldMessage; try { const error = new Error('private'); error.code = 'UI_LOCK_HELD'; throw error; } catch (error) { heldMessage = startupErrorMessage(error); } ok('22a. UI_LOCK_HELD es controlado', heldMessage === 'Job Hunter ya está abierto.' && !heldMessage.includes('private'));
  const blocker = http.createServer(); await new Promise((resolve) => blocker.listen(0, '127.0.0.1', resolve)); let conflictReleased = 0; const priorExitCode = process.exitCode; const conflict = startServer({ port: blocker.address().port, acquireUiLock: () => {}, releaseUiLock: () => { conflictReleased++; } }); const conflictError = await new Promise((resolve) => conflict.once('error', resolve)); ok('22b. EADDRINUSE es controlado', conflictError.code === 'EADDRINUSE' && conflictReleased === 1 && process.exitCode === 1); process.exitCode = priorExitCode; await new Promise((resolve) => blocker.close(resolve));

  console.log('\n### Scheduler');
  let invalid = 0; for (const v of [{ enabled: 'x', daysOfWeek: [1], time: '09:00' }, { enabled: true, daysOfWeek: [7], time: '09:00' }, { enabled: true, daysOfWeek: [], time: '09:00' }, { enabled: true, daysOfWeek: [1], time: '25:00' }]) try { validateSchedule(v); } catch (_) { invalid++; } ok('23. valida schedule completo', invalid === 4);
  const monday = new Date(2026, 8, 7, 8); const next = calculateNextRun({ enabled: true, daysOfWeek: [1], time: '09:00' }, monday); ok('24. weekday correcto', next.getDay() === 1); ok('25. hora local correcta', next.getHours() === 9); ok('26. próxima ejecución futura', next > monday);
  const missed = calculateNextRun({ enabled: true, daysOfWeek: [1], time: '09:00' }, new Date(2026, 8, 7, 14)); ok('27. no catch-up', missed.getDate() === 14); ok('28. disabled no programa', calculateNextRun({ enabled: false, daysOfWeek: [1], time: '09:00' }, monday) === null);
  const file = path.join(temp('schedule'), 'config', 'schedule.json'); const store = createScheduleStore({ filePath: file }); store.save({ enabled: true, daysOfWeek: [1, 2], time: '09:00' }); ok('29. schedule persistido', store.get().daysOfWeek.length === 2); ok('30. write atómico sin temp', fs.readdirSync(path.dirname(file)).every((n) => !n.endsWith('.tmp'))); fs.writeFileSync(file, '{bad'); let corrupt; try { store.get(); } catch (e) { corrupt = e.code; } ok('31. corrupto controlado', corrupt === 'INVALID_SCHEDULE');
  const memory = { value: { enabled: true, daysOfWeek: [1], time: '09:00' }, get() { return this.value; }, save(v) { this.value = validateSchedule(v); return this.value; } };
  const completedRunManager = { starts: 0, start: async function () { this.starts++; return { runId: `run_${this.starts}` }; }, waitForRun: async (runId) => ({ runId, status: 'COMPLETED' }) };
  let scheduled = 0; let cancelled = 0; const local = createLocalScheduler({ scheduleStore: memory, huntRunManager: completedRunManager, clock: () => monday, setTimeout: () => { scheduled++; return { unref() {} }; }, clearTimeout: () => { cancelled++; } });
  ok('32. scheduler inicia detenido', local.getStatus().nextRunAt === null && scheduled === 0); local.start(); local.start(); ok('33. start idempotente mantiene un timer', scheduled === 2 && cancelled === 1 && !!local.getStatus().nextRunAt);
  await local.trigger(); ok('34. trigger usa manager y espera COMPLETED', completedRunManager.starts === 1 && local.getStatus().lastStatus === 'COMPLETED');
  const priorScheduled = scheduled; local.update({ enabled: true, daysOfWeek: [2], time: '10:00' }); ok('35. update reemplaza timer', scheduled === priorScheduled + 1 && cancelled >= 2); local.update({ enabled: false, daysOfWeek: [2], time: '10:00' }); ok('36. disable limpia timer', local.getStatus().nextRunAt === null);
  local.update({ enabled: true, daysOfWeek: [1], time: '09:00' }); local.stop(); ok('37. stop limpia timer', local.getStatus().nextRunAt === null); const beforeRestart = scheduled; local.start(); ok('38. start después de stop vuelve a programar', scheduled === beforeRestart + 1);
  let finishManaged; const managedPendingAdapter = { start: async () => ({ runId: 'scheduled_active' }), waitForRun: () => new Promise((resolve) => { finishManaged = resolve; }) }; let activeTimers = 0; const activeScheduler = createLocalScheduler({ scheduleStore: memory, huntRunManager: managedPendingAdapter, clock: () => monday, setTimeout: () => { activeTimers++; return { unref() {} }; }, clearTimeout: () => {} }); activeScheduler.start(); const activeTrigger = activeScheduler.trigger(); await tick(); activeScheduler.stop(); finishManaged({ runId: 'scheduled_active', status: 'COMPLETED' }); await activeTrigger; ok('38a. stop durante trigger impide rearm', activeTimers === 1 && activeScheduler.getStatus().nextRunAt === null);
  const failedScheduler = createLocalScheduler({ scheduleStore: memory, huntRunManager: { start: async () => ({ runId: 'failed' }), waitForRun: async () => ({ runId: 'failed', status: 'FAILED' }) }, clock: () => monday, setTimeout: () => ({ unref() {} }), clearTimeout: () => {} }); failedScheduler.start(); await failedScheduler.trigger(); ok('38b. resultado final FAILED se conserva', failedScheduler.getStatus().lastStatus === 'FAILED');
  for (const code of ['HUNT_ALREADY_RUNNING', 'SESSION_WINDOW_OPEN', 'SETUP_REQUIRED', 'APP_SHUTTING_DOWN']) { const blockedScheduler = createLocalScheduler({ scheduleStore: memory, huntRunManager: { start: async () => { const error = new Error('private'); error.code = code; throw error; }, waitForRun: async () => ({}) }, clock: () => monday, setTimeout: () => ({ unref() {} }), clearTimeout: () => {} }); blockedScheduler.start(); await blockedScheduler.trigger(); ok(`38c. ${code} queda BLOCKED`, blockedScheduler.getStatus().lastStatus === 'BLOCKED'); }
  let installerStarts = 0; const installerBlocked = createLocalScheduler({ scheduleStore: memory, huntRunManager: { start: async () => { installerStarts++; return { runId: 'unexpected' }; }, waitForRun: async () => ({}) }, browserInstallManager: { getStatus: () => ({ status: 'RUNNING' }) }, clock: () => monday, setTimeout: () => ({ unref() {} }), clearTimeout: () => {} }); installerBlocked.start(); await installerBlocked.trigger(); ok('38d. installer RUNNING bloquea sin iniciar hunt', installerStarts === 0 && installerBlocked.getStatus().lastStatus === 'BLOCKED');
  const schedulerSource = fs.readFileSync(path.join(runtime.PROJECT_ROOT, 'src/scheduler/localScheduler.js'), 'utf8'); ok('38e. scheduler no importa hunt ni huntLock', !schedulerSource.includes("require('../hunt')") && !schedulerSource.includes('huntLock') && !schedulerSource.includes('acquireLock'));
  const missingSchedule = createScheduleStore({ filePath: path.join(temp('missing-schedule'), 'config', 'schedule.json') }); ok('38f. config faltante devuelve default disabled', missingSchedule.get().enabled === false); ok('38g. weekdays duplicados se normalizan', validateSchedule({ enabled: true, daysOfWeek: [2, 1, 2], time: '00:00' }).daysOfWeek.join(',') === '1,2');
  const preserveFile = path.join(temp('preserve-schedule'), 'config', 'schedule.json'); fs.mkdirSync(path.dirname(preserveFile), { recursive: true }); fs.writeFileSync(preserveFile, JSON.stringify({ enabled: false, daysOfWeek: [1], time: '09:00' })); const failingFs = { ...fs, renameSync: () => { throw new Error('rename failed'); } }; let writeFailed = false; try { createScheduleStore({ filePath: preserveFile, fs: failingFs }).save({ enabled: true, daysOfWeek: [2], time: '10:00' }); } catch (_) { writeFailed = true; } ok('38h. write failure preserva config anterior', writeFailed && JSON.parse(fs.readFileSync(preserveFile, 'utf8')).enabled === false);

  console.log('\n### Hunt shutdown coordination');
  const setupReady = { getStatus: () => ({ readyForHunt: true }) }; const authenticated = { isOpen: () => false, getStatus: async () => ({ state: 'AUTHENTICATED' }) };
  const idleManager = createHuntRunManager({ setupService: setupReady, sessionService: authenticated, acquireLock: () => {}, releaseLock: () => {} }); let idleResolved = false; await idleManager.waitForIdle().then(() => { idleResolved = true; }); ok('38a. waitForIdle resuelve en idle', idleResolved);
  let completeRun; const activeManager = createHuntRunManager({ setupService: setupReady, sessionService: authenticated, acquireLock: () => {}, releaseLock: () => {}, huntRunner: () => new Promise((resolve) => { completeRun = resolve; }) }); await activeManager.start(); await tick(); let activeResolved = false; const activeWait = activeManager.waitForIdle().then(() => { activeResolved = true; }); await tick(); ok('38b. waitForIdle espera hunt activo', !activeResolved); completeRun({}); await activeWait; ok('38c. completion libera waiters', activeResolved && activeManager.getStatus().status === 'COMPLETED');
  const failedManager = createHuntRunManager({ setupService: setupReady, sessionService: authenticated, acquireLock: () => {}, releaseLock: () => {}, huntRunner: async () => { throw new Error('private'); } }); await failedManager.start(); await failedManager.waitForIdle(); ok('38d. failure libera waiters de forma segura', failedManager.getStatus().status === 'FAILED' && !JSON.stringify(failedManager.getStatus()).includes('private'));
  let finishSpecific; const specificManager = createHuntRunManager({ setupService: setupReady, sessionService: authenticated, acquireLock: () => {}, releaseLock: () => {}, makeRunId: () => 'run_specific', huntRunner: () => new Promise((resolve) => { finishSpecific = resolve; }) }); const specificStart = await specificManager.start(); await tick(); let specificResolved = false; const specificWait = specificManager.waitForRun(specificStart.runId).then((result) => { specificResolved = result.status === 'COMPLETED'; }); await tick(); ok('38d1. waitForRun espera el run solicitado', !specificResolved); finishSpecific({}); await specificWait; const immediateSpecific = await specificManager.waitForRun('run_specific'); ok('38d2. run completado puede esperarse inmediatamente', specificResolved && immediateSpecific.status === 'COMPLETED'); let missingRunCode; try { specificManager.waitForRun('run_other'); } catch (error) { missingRunCode = error.code; } ok('38d3. waitForRun no confunde otro run', missingRunCode === 'HUNT_RUN_NOT_FOUND');
  idleManager.stopAccepting(); let stoppingCode; try { await idleManager.start(); } catch (error) { stoppingCode = error.code; } ok('38e. shutdown deja de aceptar hunts', stoppingCode === 'APP_SHUTTING_DOWN');
  let releaseShutdownHunt; let shutdownClosed = 0; let shutdownStopped = 0; let shutdownInstallerStopped = 0; let shutdownAcceptingStopped = 0; const shutdownLifecycle = { shuttingDown: false }; const fakeShutdownServer = new EventEmitter(); fakeShutdownServer.listening = true; fakeShutdownServer.close = (callback) => { fakeShutdownServer.listening = false; fakeShutdownServer.emit('close'); callback(); }; const coordinatedShutdown = installShutdownHandlers(fakeShutdownServer, { lifecycle: shutdownLifecycle, scheduler: { stop: () => { shutdownStopped++; } }, browserInstallManager: { stop: () => { shutdownInstallerStopped++; } }, linkedinSessionService: { close: async () => { shutdownClosed++; } }, huntRunManager: { stopAccepting: () => { shutdownAcceptingStopped++; }, waitForIdle: () => new Promise((resolve) => { releaseShutdownHunt = resolve; }) }, shutdownTimeoutMs: 10000 }); let shutdownResolved = false; const shutdownPromise = coordinatedShutdown().then(() => { shutdownResolved = true; }); await tick(); ok('38f. shutdown espera al hunt y detiene entradas', shutdownLifecycle.shuttingDown && shutdownAcceptingStopped === 1 && shutdownStopped === 1 && shutdownInstallerStopped === 1 && shutdownClosed === 1 && !shutdownResolved); releaseShutdownHunt(); await shutdownPromise; ok('38g. shutdown cierra UI después del hunt', shutdownResolved && !fakeShutdownServer.listening);
  let timeoutCallback; let timeoutClosed = 0; const timeoutServer = { listening: true, close: (callback) => { timeoutClosed++; timeoutServer.listening = false; callback(); } }; const timedShutdown = installShutdownHandlers(timeoutServer, { huntRunManager: { stopAccepting: () => {}, waitForIdle: () => new Promise(() => {}) }, setTimeout: (callback) => { timeoutCallback = callback; return 1; }, clearTimeout: () => {} }); const timedPromise = timedShutdown(); await tick(); timeoutCallback(); await timedPromise; ok('38h. timeout no cancela hunt ni borra lock', timeoutClosed === 1 && !('cancel' in timedShutdown));
  let resilientClosed = 0; const resilientServer = { listening: true, close: (callback) => { resilientClosed++; resilientServer.listening = false; callback(); } }; const originalConsoleError = console.error; console.error = () => {}; try { await installShutdownHandlers(resilientServer, { scheduler: { stop: () => { throw new Error(); } }, browserInstallManager: { stop: () => { throw new Error(); } }, linkedinSessionService: { close: async () => { throw new Error(); } } })(); } finally { console.error = originalConsoleError; } ok('38i. fallos de servicios no bloquean server close', resilientClosed === 1);
  let finishScheduledRun; const sharedManager = createHuntRunManager({ setupService: setupReady, sessionService: authenticated, acquireLock: () => {}, releaseLock: () => {}, makeRunId: () => 'run_scheduled', huntRunner: () => new Promise((resolve) => { finishScheduledRun = resolve; }) }); let scheduledTimers = 0; const sharedScheduler = createLocalScheduler({ scheduleStore: memory, huntRunManager: sharedManager, clock: () => monday, setTimeout: () => { scheduledTimers++; return { unref() {} }; }, clearTimeout: () => {} }); sharedScheduler.start(); const sharedTrigger = sharedScheduler.trigger(); await tick(); ok('38j. scheduled hunt visible en HuntRunManager', sharedManager.getStatus().runId === 'run_scheduled' && sharedManager.getStatus().status === 'RUNNING'); let sharedClosed = 0; const sharedServer = { listening: true, close: (callback) => { sharedClosed++; sharedServer.listening = false; callback(); } }; const sharedShutdown = installShutdownHandlers(sharedServer, { scheduler: sharedScheduler, huntRunManager: sharedManager, linkedinSessionService: { close: async () => {} } }); let sharedShutdownDone = false; const sharedShutdownPromise = sharedShutdown().then(() => { sharedShutdownDone = true; }); await tick(); ok('38k. shutdown espera scheduled hunt', !sharedShutdownDone && sharedClosed === 0); finishScheduledRun({}); await sharedTrigger; await sharedShutdownPromise; ok('38l. scheduled hunt termina sin rearm tras shutdown', sharedShutdownDone && sharedClosed === 1 && scheduledTimers === 1 && sharedScheduler.getStatus().nextRunAt === null);

  console.log('\n### Browser installer/launcher');
  let finishInstall; const installing = new Promise((r) => { finishInstall = r; }); const manager = createBrowserInstallManager({ installer: () => installing }); ok('39. instalación async', manager.start().status === 'RUNNING'); let duplicate; try { manager.start(); } catch (e) { duplicate = e.code; } ok('40. duplicada bloqueada', duplicate === 'BROWSER_INSTALL_RUNNING'); finishInstall(); await tick(); await tick(); ok('41. éxito registrado', manager.getStatus().status === 'COMPLETED');
  const bad = createBrowserInstallManager({ installer: async () => { throw new Error('C:\\private'); } }); bad.start(); await tick(); await tick(); ok('42. fallo registrado', bad.getStatus().status === 'FAILED'); ok('43. fallo sanitizado', !JSON.stringify(bad.getStatus()).includes('private'));
  let spawnContract; const fakeChild = new EventEmitter(); fakeChild.kill = () => {}; defaultInstaller({ appDir: 'C:\\app con espacios', browsersDir: 'C:\\runtime con espacios\\browsers', nodeExecutable: 'C:\\node gestionado\\node.exe', env: { SAFE: 'yes' }, resolvePackage: () => 'C:\\app con espacios\\node_modules\\playwright\\package.json', spawnChild: (command, args, options) => { spawnContract = { command, args, options }; return fakeChild; } }); ok('43a. Playwright usa CLI y ruta administrada', spawnContract.command === 'C:\\node gestionado\\node.exe' && spawnContract.args[0] === 'C:\\app con espacios\\node_modules\\playwright\\cli.js' && spawnContract.args.join('|').includes('install|chromium') && spawnContract.options.env.PLAYWRIGHT_BROWSERS_PATH === 'C:\\runtime con espacios\\browsers' && spawnContract.options.shell === false);
  const exportsFixture = temp('playwright-exports'); const exportsPackageDir = path.join(exportsFixture, 'node_modules', 'playwright'); fs.mkdirSync(exportsPackageDir, { recursive: true }); fs.writeFileSync(path.join(exportsPackageDir, 'package.json'), JSON.stringify({ name: 'playwright', version: '1.62.1', exports: { './package.json': './package.json' } })); fs.writeFileSync(path.join(exportsPackageDir, 'cli.js'), ''); let exportsCli; defaultInstaller({ appDir: exportsFixture, browsersDir: path.join(exportsFixture, 'browsers'), nodeExecutable: 'node.exe', spawnChild: (_command, args) => { exportsCli = args[0]; return fakeChild; } }); const installerSource = fs.readFileSync(path.join(runtime.PROJECT_ROOT, 'src/install/browserInstallManager.js'), 'utf8'); ok('43a1. package.json exportado deriva CLI físico existente', exportsCli === path.join(exportsPackageDir, 'cli.js') && fs.existsSync(exportsCli)); ok('43a2. installer no depende del subpath no exportado', installerSource.includes("resolvePackage('playwright/package.json')") && !installerSource.includes("'playwright/cli'"));
  let stoppedChild = 0; const ownedChild = new EventEmitter(); ownedChild.kill = () => { stoppedChild++; ownedChild.emit('exit', 0); }; const stoppable = createBrowserInstallManager({ installer: () => ownedChild }); stoppable.start(); const stoppedStatus = stoppable.stop(); ok('43b. stop mata sólo el child propio y fija estado', stoppedChild === 1 && stoppedStatus.status === 'FAILED' && stoppedStatus.error.code === 'BROWSER_INSTALL_STOPPED');
  let timeoutFn; let timerCleared = 0; let timeoutKilled = 0; const timeoutChild = new EventEmitter(); timeoutChild.kill = () => { timeoutKilled++; timeoutChild.emit('exit', 0); }; const expiring = createBrowserInstallManager({ installer: () => timeoutChild, setTimeout: (fn) => { timeoutFn = fn; return 7; }, clearTimeout: (id) => { if (id === 7) timerCleared++; }, timeoutMs: 50 }); expiring.start(); timeoutFn(); ok('43c. timeout queda terminal pese a exit tardío', timeoutKilled === 1 && timerCleared === 1 && expiring.getStatus().error.code === 'BROWSER_INSTALL_TIMEOUT');
  const launcher = fs.readFileSync(path.join(runtime.PROJECT_ROOT, 'start-job-hunter.cmd'), 'utf8'); ok('44. launcher usa runtime administrado', launcher.includes('runtime-managed\\node\\node.exe')); ok('45. no cambia ExecutionPolicy', !/Set-ExecutionPolicy/i.test(launcher)); ok('46. no requiere admin', !/runas|\/RL HIGHEST/i.test(launcher)); ok('47. abre localhost tras health', launcher.includes('http://127.0.0.1:4173/api/health')); ok('48. sin paths developer', !/C:\\dev|C:\\Users/i.test(launcher));
  ok('48a. health rechaza servicio ajeno', /\$r\.status -eq 'ok' -and \$r\.app -eq 'job-hunter'/.test(launcher)); ok('48b. launcher cita Node y scripts con espacios', launcher.includes('"%JH_NODE%" "%~dp0scripts\\bootstrap.js"') && launcher.includes('"%JH_NODE%" "%~dp0src\\ui\\server.js"')); ok('48c. launcher no usa npm ni cambia PATH', !/\bnpm(?:\.cmd)?\b/i.test(launcher) && !/setx?\s+PATH/i.test(launcher));
  const frontendHtml = fs.readFileSync(path.join(runtime.PROJECT_ROOT, 'src/ui/public/index.html'), 'utf8'); const frontendJs = fs.readFileSync(path.join(runtime.PROJECT_ROOT, 'src/ui/public/app.js'), 'utf8'); ok('48d. UI conserva mapping weekday 0-6', ['value="0"', 'value="1"', 'value="2"', 'value="3"', 'value="4"', 'value="5"', 'value="6"'].every((value) => frontendHtml.includes(value))); ok('48e. UI informa que app debe permanecer abierta', frontendHtml.includes('Job Hunter debe permanecer abierto')); ok('48f. UI convierte nextRunAt a hora local', frontendJs.includes('new Date(schedule.nextRunAt).toLocaleString()'));
  ok('49. n8n no es dependencia', !JSON.stringify(require('../../package.json').dependencies).toLowerCase().includes('n8n')); ok('50. trigger/n8n permanecen', fs.existsSync(path.join(runtime.PROJECT_ROOT, 'src/trigger/server.js')) && fs.existsSync(path.join(runtime.PROJECT_ROOT, 'n8n/job-hunter-daily-hunt.json')));
  const serverSource = fs.readFileSync(path.join(runtime.PROJECT_ROOT, 'src/ui/server.js'), 'utf8'); ok('51. shutdown no elimina hunt.lock directamente', !serverSource.includes("require('../domain/huntLock')") && !serverSource.includes('releaseLock(')); ok('52. tests usan instalador inyectado y no Task Scheduler', manager.getStatus().status === 'COMPLETED' && !launcher.toLowerCase().includes('schtasks'));
  console.log(`\nPhase 4: ${passed} passed, ${failed} failed`); if (failed) process.exitCode = 1;
}
run().catch((e) => { console.error(e); process.exitCode = 1; });
